# Generated by Django 4.2.3 on 2023-07-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_melody', '0002_alter_song_audio_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blue_team_score', models.IntegerField(default=0)),
                ('red_team_score', models.IntegerField(default=0)),
            ],
        ),
    ]
