# Generated by Django 4.2.3 on 2023-07-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_melody', '0003_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='drawn',
            field=models.BooleanField(default=False),
        ),
    ]
