# Generated by Django 4.2.3 on 2023-07-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_melody', '0005_song_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genres',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(upload_to='songs/'),
        ),
    ]
