# Generated by Django 4.2.4 on 2023-08-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_melody', '0006_song_genres_alter_song_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='tip',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
