# Generated by Django 4.2.3 on 2023-08-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_melody', '0007_song_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='polish',
            field=models.BooleanField(default=False),
        ),
    ]
